name: Contexts Demo
run-name: Deployed by ${{ github.actor }} to ${{ github.ref_name }}
on: push
env:
  NAME: Ajay Naidu
jobs:
  job1:    
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ env.NAME }}"
      
