name: Enviroment Demo
on: push
jobs:
  job1:
    environment: DEV
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ vars.MY_VAR }}"
    - run: echo "${{ secrets.MY_SECRET }}" | base64 | base64 -d
