name: Sample Workflow
on: workflow_dispatch
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/ajnaidu/sample.git
    - run: mvn clean install
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo "deployed application"
